# Generated by Django 3.0 on 2021-07-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=11)),
                ('member', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=100)),
                ('msg', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
    ]
